#!/usr/bin/env bash
/usr/bin/env git clone https://github.com/No5stranger/git-config.git /tmp/git-config
if [ -f $HOME/.gitconfig ]
then
    mv $HOME/.gitconfig $HOME/.gitconfig.bak
fi
cp /tmp/git-config/gitconfig $HOME/.gitconfig
